title: EEA aa2024-2025
description: Tutorial for Bioinformatic Analysis of Epigenetics Data
theme: just-the-docs
color_scheme: light
nav_enabled: true
exclude: "backup/"

url: https://gabbo89.github.io/EEA2024
logo: "https://www.sisfvg.it/sites/default/files/logoUniud-small.png"

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
aux_links:
  "Analisi di Dati Epigenetici on GitHub":
    - "//github.com/gabbo89/EEA2024"